syntax = "proto3";

package user_service.v1;

import "common/v1/user.proto";
import "common/vendor/validate.proto";

option go_package = "proto/user_service";

message LogInRequest {
  string username = 1[
    (buf.validate.field).string.min_len = 1
  ];
  string password = 2[
    (buf.validate.field).string.min_len = 8
  ];
}

message LogInResponse {
  string token = 1;
}

message CreateUserRequest{
  string username = 1[
    (buf.validate.field).string.min_len = 1
  ];
  string password = 2[
    (buf.validate.field).string.min_len = 8
  ];
  string group_id = 3[
    (buf.validate.field).string = {
    uuid: true
    }
  ];
  string idempot_key = 4[
    (buf.validate.field).string = {
    uuid: true
    }
  ];
}

message CreateUserResponse {
  common.v1.User user = 1;
}

message GetGroupsRequest {
  int32 cursor = 1;
  int32 limit  = 2;
}

message GetGroupsResponse {
  repeated common.v1.UserGroup groups = 1;
  int32                        next   = 2;
}

message GetUserRequest {
  string user_id = 1[
    (buf.validate.field).string = {
    uuid: true
    }
  ];
}

message GetUserResponse {
  common.v1.User user = 1;
}

message GetPermissionsRequest {
  string user_id = 1[
    (buf.validate.field).string = {
    uuid: true
    }
  ];
}

message GetPermissionsResponse {
  repeated common.v1.UserPermission user_permissions = 1;
}