syntax = "proto3";

package user_service.v1;

import "user_service/v1/messages.proto";
import "google/protobuf/empty.proto";

option go_package = "proto/user_service";

service UserService {
  rpc LogIn(LogInRequest) returns (LogInResponse);
  rpc LogOut(google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
  rpc GetGroups(GetGroupsRequest) returns (GetGroupsResponse);
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc GetPermissions(GetPermissionsRequest) returns (GetPermissionsResponse);
}

