// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc_gen

import (
	"github.com/google/uuid"
)

type GroupPermissions struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

type Groups struct {
	Name string
	ID   uuid.UUID
}

type Permissions struct {
	Name string
	ID   uuid.UUID
}

type Users struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	GroupID      uuid.UUID
}
