// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_queries.sql

package sqlc_gen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into Users (id, username, password_hash, group_id) values ($1, $2, $3, $4)
returning id
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	GroupID      uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.GroupID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users u where u.id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
select
    u.username,
    u.password_hash,
    u."id",
    g."name" as group_name,
    g."id" as group_uuid,
    JSON_AGG(
        JSON_BUILD_OBJECT(
            'ID', p.id,
            'Name', p.name
        ) order by p.id
    ) as permissions
from
    users u
    left join "groups" g on g.id = u.group_id
    left join group_permissions gp on g.id = gp.group_id
    left join permissions p on p.id = gp.permission_id
where
	u."id" = $1
group by
    u.username,
    u.password_hash,
    u."id",
    g."name",
    g."id"
`

type GetUserByIDRow struct {
	Username     string
	PasswordHash string
	ID           uuid.UUID
	GroupName    sql.NullString
	GroupUuid    uuid.NullUUID
	Permissions  json.RawMessage
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.ID,
		&i.GroupName,
		&i.GroupUuid,
		&i.Permissions,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select
    u.username,
    u.password_hash,
    u."id",
    g."name" as group_name,
    g."id" as group_uuid,
    JSON_AGG(
        JSON_BUILD_OBJECT(
            'ID', p.id,
            'Name', p.name
        ) order by p.id
    ) as permissions
from
    users u
    left join "groups" g on g.id = u.group_id
    left join group_permissions gp on g.id = gp.group_id
    left join permissions p on p.id = gp.permission_id
where
	u.username = $1
group by
    u.username,
    u.password_hash,
    u."id",
    g."name",
    g."id"
`

type GetUserByUsernameRow struct {
	Username     string
	PasswordHash string
	ID           uuid.UUID
	GroupName    sql.NullString
	GroupUuid    uuid.NullUUID
	Permissions  json.RawMessage
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.ID,
		&i.GroupName,
		&i.GroupUuid,
		&i.Permissions,
	)
	return i, err
}

const getUserList = `-- name: GetUserList :many
select
    u.username,
    u.password_hash,
    u."id",
    g."name" as group_name,
    g."id" as group_uuid,
	JSON_AGG(
        JSON_BUILD_OBJECT(
            'ID', p.id,
            'Name', p.name
        ) order by p.id
    ) as permissions
from
    users u
    left join "groups" g on g.id = u.group_id
    left join group_permissions gp on g.id = gp.group_id
    left join permissions p on p.id = gp.permission_id
group by
	u.id,
    u.username,
    u.password_hash,
    u."id",
    g."name",
    g."id"
order by u.id
limit $1 offset $2
`

type GetUserListParams struct {
	Limit  int32
	Offset int32
}

type GetUserListRow struct {
	Username     string
	PasswordHash string
	ID           uuid.UUID
	GroupName    sql.NullString
	GroupUuid    uuid.NullUUID
	Permissions  json.RawMessage
}

func (q *Queries) GetUserList(ctx context.Context, arg GetUserListParams) ([]GetUserListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserListRow
	for rows.Next() {
		var i GetUserListRow
		if err := rows.Scan(
			&i.Username,
			&i.PasswordHash,
			&i.ID,
			&i.GroupName,
			&i.GroupUuid,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
update Users u set
    "username" = $1,
    "password_hash" = $2,
    group_id = $3
where
    u.id = $4
`

type UpdateUserParams struct {
	Username     string
	PasswordHash string
	GroupID      uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.PasswordHash,
		arg.GroupID,
		arg.ID,
	)
	return err
}
