-- +goose Up
SELECT 'up SQL query';

CREATE TABLE public.group_permissions (
    group_id uuid NOT NULL,
    permission_id uuid NOT NULL 
);

CREATE TABLE public.groups (
    id integer NOT NULL,
    name character varying NOT NULL,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.permissions (
    id integer NOT NULL,
    name character varying NOT NULL,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL
);



ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.users (
    id integer NOT NULL,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    username character varying NOT NULL,
    password_hash character varying(128) NOT NULL,
    group_id uuid NOT NULL
);



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.group_permissions
    ADD CONSTRAINT group_permissions_pk PRIMARY KEY (group_id, permission_id);



ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_name_key UNIQUE (name);

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_uuid_key UNIQUE (uuid);


ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permission_pk PRIMARY KEY (id);


ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_unique UNIQUE (name);


ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_unique_1 UNIQUE (uuid);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_uuid_key UNIQUE (uuid);


ALTER TABLE ONLY public.group_permissions
    ADD CONSTRAINT group_permissions_groups_fk FOREIGN KEY (group_id) REFERENCES public.groups(uuid) ON DELETE CASCADE;


ALTER TABLE ONLY public.group_permissions
    ADD CONSTRAINT group_permissions_permissions_fk FOREIGN KEY (permission_id) REFERENCES public.permissions(uuid) ON DELETE CASCADE;


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(uuid);



-- +goose Down
SELECT 'down SQL query';

DROP TABLE public.users;

DROP TABLE public.group_permissions;

DROP TABLE public.groups;

DROP TABLE public.permissions;
