syntax = "proto3";

package common.v1;

enum UserPermission{
  USER_PERMISSION_UNSPECIFIED = 0;
  
  USER_PERMISSION_SET_PRICE = 1;

  USER_PERMISSION_CREATE_MARKET = 2;
  USER_PERMISSION_READ_OPEN_MARKETS = 3;
  USER_PERMISSION_READ_PRIVATE_MARKETS = 4;
  USER_PERMISSION_UPDATE_MARKET = 5;
  USER_PERMISSION_DELETE_MARKET = 6;
  
  USER_PERMISSION_CREATE_USER = 7;
  USER_PERMISSION_DELETE_USER = 8;
  USER_PERMISSION_UPDATE_USER = 9;
  USER_PERMISSION_UPDATE_SELF = 10;

  USER_PERMISSION_MAKE_DEAL = 11;
}
