// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_queries.sql

package sqlc_gen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addPermissionsToGroup = `-- name: AddPermissionsToGroup :exec
insert into group_permissions (group_id, permission_id) values ($1, $2)
`

type AddPermissionsToGroupParams struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) AddPermissionsToGroup(ctx context.Context, arg AddPermissionsToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionsToGroup, arg.GroupID, arg.PermissionID)
	return err
}

const createGroup = `-- name: CreateGroup :one
insert into groups (name) values ($1)
returning id
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteGroup = `-- name: DeleteGroup :exec
delete from groups where id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
select
    g.name,
    g.id as "id",
    JSON_AGG(
        JSON_BUILD_OBJECT(
            'ID', p.id,
            'Name', p.name
        ) order by p.id
    ) as permissions
from
    groups g
    join group_permissions gp on g.id = gp.group_id
    join permissions p on p.id = gp.permission_id
where
    g.id = $1
group by g.name, g.id
`

type GetGroupByIDRow struct {
	Name        string
	ID          uuid.UUID
	Permissions json.RawMessage
}

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (GetGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i GetGroupByIDRow
	err := row.Scan(&i.Name, &i.ID, &i.Permissions)
	return i, err
}

const getGroupList = `-- name: GetGroupList :many
select
    g.name,
    g.id as "id",
    JSON_AGG(
        JSON_BUILD_OBJECT(
            'ID', p.id,
            'Name', p.name
        ) order by p.id
    ) as permissions,
    g.id as created
from
    groups g
    join group_permissions gp on g.id = gp.group_id
    join permissions p on p.id = gp.permission_id
where g.id >= $1
group by g.name, g.id
limit $2
`

type GetGroupListParams struct {
	ID    uuid.UUID
	Limit int32
}

type GetGroupListRow struct {
	Name        string
	ID          uuid.UUID
	Permissions json.RawMessage
	Created     uuid.UUID
}

func (q *Queries) GetGroupList(ctx context.Context, arg GetGroupListParams) ([]GetGroupListRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupList, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupListRow
	for rows.Next() {
		var i GetGroupListRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.Permissions,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupPermissions = `-- name: GetGroupPermissions :many
select
    p.name,
    p.id
from
    permissions p
    join group_permissions gp on gp.permission_id = p.id
where gp.group_id = $1
`

func (q *Queries) GetGroupPermissions(ctx context.Context, groupID uuid.UUID) ([]Permissions, error) {
	rows, err := q.db.QueryContext(ctx, getGroupPermissions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permissions
	for rows.Next() {
		var i Permissions
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionsFromGroup = `-- name: RemovePermissionsFromGroup :exec
delete from group_permissions gp where gp.group_id = $1 and gp.permission_id = $2
`

type RemovePermissionsFromGroupParams struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) RemovePermissionsFromGroup(ctx context.Context, arg RemovePermissionsFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionsFromGroup, arg.GroupID, arg.PermissionID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
update groups g set
    "name" = $1
where g.id = $2
`

type UpdateGroupParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.Name, arg.ID)
	return err
}
