// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_queries.sql

package sqlc_gen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addPermissionsToGroup = `-- name: AddPermissionsToGroup :exec
insert into group_permissions (group_id, permission_id) values ($1, $2)
`

type AddPermissionsToGroupParams struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) AddPermissionsToGroup(ctx context.Context, arg AddPermissionsToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionsToGroup, arg.GroupID, arg.PermissionID)
	return err
}

const createGroup = `-- name: CreateGroup :one
insert into groups (name) values ($1)
returning uuid
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const deleteGroup = `-- name: DeleteGroup :exec
delete from groups where uuid = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, argUuid)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
select 
    g.name,
    g.uuid as "id",
    JSON_AGG(
        JSON_BUILD_OBJECT(
            p.uuid, p.name
        )
    )
from 
    groups g
    join group_permissions gp on g.id = gp.group_id
    join permissions p on p.id = gp.permission_id
where 
    g.uuid = $1
group by g.name, g.uuid
`

type GetGroupByIDRow struct {
	Name    string
	ID      uuid.UUID
	JsonAgg json.RawMessage
}

func (q *Queries) GetGroupByID(ctx context.Context, argUuid uuid.UUID) (GetGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, argUuid)
	var i GetGroupByIDRow
	err := row.Scan(&i.Name, &i.ID, &i.JsonAgg)
	return i, err
}

const getGroupList = `-- name: GetGroupList :many
select 
    g.name,
    g.uuid as "id",
    JSON_AGG(
        JSON_BUILD_OBJECT(
            p.uuid, p.name
        )
    )
from 
    groups g
    join group_permissions gp on g.id = gp.group_id
    join permissions p on p.id = gp.permission_id
where 
    g.uuid = $1
group by g.name, g.uuid
`

type GetGroupListRow struct {
	Name    string
	ID      uuid.UUID
	JsonAgg json.RawMessage
}

func (q *Queries) GetGroupList(ctx context.Context, argUuid uuid.UUID) ([]GetGroupListRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupList, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupListRow
	for rows.Next() {
		var i GetGroupListRow
		if err := rows.Scan(&i.Name, &i.ID, &i.JsonAgg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupPermissions = `-- name: GetGroupPermissions :many
select
    p.name,
    p.uuid
from 
    permissions p
    join group_permissions gp on gp.permission_id = p.id
where gp.group_id = $1
`

type GetGroupPermissionsRow struct {
	Name string
	Uuid uuid.UUID
}

func (q *Queries) GetGroupPermissions(ctx context.Context, groupID uuid.UUID) ([]GetGroupPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupPermissions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPermissionsRow
	for rows.Next() {
		var i GetGroupPermissionsRow
		if err := rows.Scan(&i.Name, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionsFromGroup = `-- name: RemovePermissionsFromGroup :exec
delete from group_permissions gp where gp.group_id = $1 and gp.permission_id = $2
`

type RemovePermissionsFromGroupParams struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) RemovePermissionsFromGroup(ctx context.Context, arg RemovePermissionsFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionsFromGroup, arg.GroupID, arg.PermissionID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
update groups g set 
    "name" = $1
`

func (q *Queries) UpdateGroup(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateGroup, name)
	return err
}
