// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc_gen

import (
	"github.com/google/uuid"
)

type GroupPermissions struct {
	GroupID      uuid.UUID
	PermissionID uuid.UUID
}

type Groups struct {
	ID   int32
	Name string
	Uuid uuid.UUID
}

type Permissions struct {
	ID   int32
	Name string
	Uuid uuid.UUID
}

type Users struct {
	ID           int32
	Uuid         uuid.UUID
	Username     string
	PasswordHash string
	GroupID      uuid.UUID
}
