// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_queries.sql

package sqlc_gen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into Users (username, password_hash, group_id) values ($1, $2, $3)
returning uuid
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	GroupID      uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.GroupID)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users u where u.uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, argUuid)
	return err
}

const getUserByID = `-- name: GetUserByID :one
select
    u.username,
    u.password_hash,
    u."uuid",
    g."name",
    g."uuid" as group_uuid,
    JSON_AGG(
        JSON_BUILD_OBJECT(
            p.uuid, p.name
        )
    ) as permissions
from
    users u
    join "groups" g on g.id = u.group_id 
    join group_permissions gp on g.id = gp.group_id
    join permissions p on p.id = gp.permission_id
where
	u."uuid" = $1
`

type GetUserByIDRow struct {
	Username     string
	PasswordHash string
	Uuid         uuid.UUID
	Name         string
	GroupUuid    uuid.UUID
	Permissions  json.RawMessage
}

func (q *Queries) GetUserByID(ctx context.Context, argUuid uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, argUuid)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.Uuid,
		&i.Name,
		&i.GroupUuid,
		&i.Permissions,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select
    u.username,
    u.password_hash,
    u."uuid",
    g."name",
    g."uuid" as group_uuid,
    JSON_AGG(
        JSON_BUILD_OBJECT(
            p.uuid, p.name
        )
    ) as permissions
from
    users u
    join "groups" g on g.uuid = u.group_id
    join group_permissions gp on g.id = gp.group_id
    join permissions p on p.id = gp.permission_id
where
	u.username = $1
group by 
    u.username,
    u.password_hash,
    u."uuid",
    g."name",
    g."uuid"
`

type GetUserByUsernameRow struct {
	Username     string
	PasswordHash string
	Uuid         uuid.UUID
	Name         string
	GroupUuid    uuid.UUID
	Permissions  json.RawMessage
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.Uuid,
		&i.Name,
		&i.GroupUuid,
		&i.Permissions,
	)
	return i, err
}

const getUserList = `-- name: GetUserList :many
select
    u.username,
    u.password_hash,
    u."uuid",
    g."name",
    g."uuid" as group_uuid
from
    users u
    join "groups" g on g.id = u.group_id  
limit
    $1 offset $2
`

type GetUserListParams struct {
	Limit  int32
	Offset int32
}

type GetUserListRow struct {
	Username     string
	PasswordHash string
	Uuid         uuid.UUID
	Name         string
	GroupUuid    uuid.UUID
}

func (q *Queries) GetUserList(ctx context.Context, arg GetUserListParams) ([]GetUserListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserListRow
	for rows.Next() {
		var i GetUserListRow
		if err := rows.Scan(
			&i.Username,
			&i.PasswordHash,
			&i.Uuid,
			&i.Name,
			&i.GroupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
update Users u set
    "username" = $1,
    "password_hash" = $2,
    group_id = $3
where
    u.uuid = $4
`

type UpdateUserParams struct {
	Username     string
	PasswordHash string
	GroupID      uuid.UUID
	Uuid         uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.PasswordHash,
		arg.GroupID,
		arg.Uuid,
	)
	return err
}
